// <auto-generated />
using System;
using Brewskii.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Brewskii.Migrations
{
    [DbContext(typeof(BrewskiiContext))]
    partial class BrewskiiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Brewskii.Models.Beer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BeerName");

                    b.Property<string>("BeerType");

                    b.Property<DateTime>("DateTried");

                    b.Property<decimal>("Price");

                    b.Property<decimal>("Rating");

                    b.HasKey("ID");

                    b.ToTable("Beer");
                });
#pragma warning restore 612, 618
        }
    }
}
